# Form implementation generated from reading ui file 'login_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_animals_login(object):
    def setupUi(self, animals_login):
        animals_login.setObjectName("animals_login")
        animals_login.resize(583, 402)
        animals_login.setStyleSheet("#btn_login:hover , #btn_register:hover , #btn_cancel:hover{\n"
"border:2px solid black;\n"
"background-color:gray;\n"
"color:white;\n"
"}\n"
"\n"
"#btn_login , #btn_register , #btn_cancel{\n"
"border:2px solid #cccccc;\n"
"padding:2px 2px;\n"
"border-bottom-right-radius:30px;\n"
"}\n"
"\n"
"#login_user:hover , #login_pwd:hover{\n"
"border:2px solid black;\n"
"}\n"
"#login_user , #login_pwd{\n"
"border:2px solid #cccccc;\n"
"}\n"
"#login_user_title , #login_pwd_title{\n"
"background-color:#cccccc;\n"
"border-bottom-right-radius:30px;\n"
"}\n"
"#label{\n"
"border-radius:50px;\n"
"background-color:white;\n"
"}\n"
"")
        #animals_login.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        #animals_login.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label = QtWidgets.QLabel(animals_login)
        self.label.setGeometry(QtCore.QRect(20, 10, 541, 371))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(animals_login)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.login_user_title = QtWidgets.QLabel(animals_login)
        self.login_user_title.setGeometry(QtCore.QRect(100, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.login_user_title.setFont(font)
        self.login_user_title.setObjectName("login_user_title")
        self.login_pwd_title = QtWidgets.QLabel(animals_login)
        self.login_pwd_title.setGeometry(QtCore.QRect(100, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.login_pwd_title.setFont(font)
        self.login_pwd_title.setObjectName("login_pwd_title")
        self.login_user = QtWidgets.QLineEdit(animals_login)
        self.login_user.setGeometry(QtCore.QRect(200, 130, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.login_user.setFont(font)
        self.login_user.setObjectName("login_user")
        self.login_pwd = QtWidgets.QLineEdit(animals_login)
        self.login_pwd.setGeometry(QtCore.QRect(200, 170, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.login_pwd.setFont(font)
        self.login_pwd.setText("")
        self.login_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.login_pwd.setObjectName("login_pwd")
        self.login_msg = QtWidgets.QLabel(animals_login)
        self.login_msg.setGeometry(QtCore.QRect(70, 310, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.login_msg.setFont(font)
        self.login_msg.setText("")
        self.login_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_msg.setObjectName("login_msg")
        self.layoutWidget = QtWidgets.QWidget(animals_login)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 230, 343, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.btn_register = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.btn_register.setFont(font)
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout.addWidget(self.btn_register)
        self.btn_cancel = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)

        self.retranslateUi(animals_login)
        QtCore.QMetaObject.connectSlotsByName(animals_login)

    def retranslateUi(self, animals_login):
        _translate = QtCore.QCoreApplication.translate
        animals_login.setWindowTitle(_translate("animals_login", "Frame"))
        self.label_2.setText(_translate("animals_login", "新北市動保處 環境偵測系統"))
        self.login_user_title.setText(_translate("animals_login", "帳號"))
        self.login_pwd_title.setText(_translate("animals_login", "密碼"))
        self.btn_login.setText(_translate("animals_login", "登入"))
        self.btn_register.setText(_translate("animals_login", "註冊"))
        self.btn_cancel.setText(_translate("animals_login", "取消"))
