# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_animals_login(object):
    def setupUi(self, animals_login):
        animals_login.setObjectName("animals_login")
        animals_login.resize(500, 400)
        animals_login.setStyleSheet("#login_pwd , #login_user{\n"
"background-color:#cccccc;\n"
"border-color:gray;\n"
"}\n"
"#label_2 , #label_4{\n"
"background-color:#cccccc;\n"
"border-bottom-right-radius:30px;\n"
"}\n"
"#label{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}\n"
"#btn_login , #btn_register , #btn_cancel{\n"
"background-color:#cccccc;\n"
"}\n"
"#btn_login:hover , #btn_register:hover , #btn_cancel:hover{\n"
"background-color:gray;\n"
"color:white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(animals_login)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 461, 301))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.login_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.login_pwd.setGeometry(QtCore.QRect(160, 170, 271, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.login_pwd.setFont(font)
        self.login_pwd.setStyleSheet("")
        self.login_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.login_pwd.setObjectName("login_pwd")
        self.login_msg = QtWidgets.QLabel(self.centralwidget)
        self.login_msg.setGeometry(QtCore.QRect(60, 290, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.login_msg.setFont(font)
        self.login_msg.setStyleSheet("")
        self.login_msg.setText("")
        self.login_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_msg.setObjectName("login_msg")
        self.login_user = QtWidgets.QLineEdit(self.centralwidget)
        self.login_user.setGeometry(QtCore.QRect(160, 120, 271, 30))
        self.login_user.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.login_user.setFont(font)
        self.login_user.setStyleSheet("")
        self.login_user.setObjectName("login_user")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 50, 231, 21))
        self.label_3.setSizeIncrement(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 61, 30))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 170, 60, 30))
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 240, 229, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("")
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.btn_register = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_register.setFont(font)
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout.addWidget(self.btn_register)
        self.btn_cancel = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        animals_login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(animals_login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 24))
        self.menubar.setObjectName("menubar")
        animals_login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(animals_login)
        self.statusbar.setObjectName("statusbar")
        animals_login.setStatusBar(self.statusbar)

        self.retranslateUi(animals_login)
        QtCore.QMetaObject.connectSlotsByName(animals_login)

    def retranslateUi(self, animals_login):
        _translate = QtCore.QCoreApplication.translate
        animals_login.setWindowTitle(_translate("animals_login", "Login"))
        self.login_pwd.setToolTip(_translate("animals_login", "<html><head/><body><p>輸入密碼</p></body></html>"))
        self.login_pwd.setPlaceholderText(_translate("animals_login", "password"))
        self.login_user.setToolTip(_translate("animals_login", "<html><head/><body><p>輸入帳號</p></body></html>"))
        self.login_user.setPlaceholderText(_translate("animals_login", "username"))
        self.label_3.setText(_translate("animals_login", "新北市動保處 環境偵測系統"))
        self.label_2.setText(_translate("animals_login", "帳號"))
        self.label_4.setText(_translate("animals_login", "密碼"))
        self.btn_login.setToolTip(_translate("animals_login", "<html><head/><body><p>登入</p></body></html>"))
        self.btn_login.setText(_translate("animals_login", "登入"))
        self.btn_register.setToolTip(_translate("animals_login", "<html><head/><body><p>註冊一般使用者</p></body></html>"))
        self.btn_register.setText(_translate("animals_login", "註冊"))
        self.btn_cancel.setToolTip(_translate("animals_login", "<html><head/><body><p>取消</p></body></html>"))
        self.btn_cancel.setText(_translate("animals_login", "取消"))
